[[plugins]]
repo = 'Shougo/denite.nvim'
on_cmd = 'Denite'
hook_post_source = '''
    " デフォルトのプロンプトを変更
    call denite#custom#option('default', 'prompt', '>')

    " denite/insert モード時は C- で移動できるようにする
    call denite#custom#map('insert', '<C-n>', '<denite:move_to_next_line>')
    call denite#custom#map('insert', '<C-p>', '<denite:move_to_previous_line>')

    " tabopen/vsplitのキーバインド割当
    call denite#custom#map('insert', '<C-t>', '<denite:do_action:tabopen>')
    call denite#custom#map('insert', '<C-v>', '<denite:do_action:vsplit>')

    " grepとファイル検索をagに置換
    if executable('ag')
        call denite#custom#var('file/rec', 'command', ['ag', '--follow', '--nocolor', '--nogroup', '-g', ''])
        call denite#custom#var('grep', 'command', ['ag'])
        call denite#custom#var('grep', 'default_opts', ['-i', '--vimgrep'])
        call denite#custom#var('grep', 'recursive_opts', [])
        call denite#custom#var('grep', 'pattern_opt', [])
        call denite#custom#var('grep', 'separator', ['--'])
        call denite#custom#var('grep', 'final_opts', [])
    endif
'''
